# version: "3.8"
# services:
#   server:
#     build: .
#     container_name: server
#     ports:
#       - "${HTTP_PORT:-8000}:8000"
#     volumes:
#       - ./:/var/www/
#       - /var/www/vendor
#     depends_on:
#       - mysql
#     links:
#       - mysql
#   mysql:
#     image: mysql:8.0.22
#     container_name: mysql
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       MYSQL_DATABASE: 'todolistdocker'
#       MYSQL_USER: 'root'
#       MYSQL_ROOT_PASSWORD: 'rewan123'
#     ports:
#       - ${MYSQL_PORT:-3306}:3306
#     volumes:
#       - ./mysql/init.sql:/data/application/init.sql
#       - mysql_data:/var/lib/mysql
#   client:
#     build:
#       context: .
#       dockerfile: ./Dockerfile.node
#     container_name: client
#     volumes:
#       - ./:/var/www/
#       - /var/www/node_modules
#     depends_on:
#       - "server"
# volumes:
#   mysql_data:






# version: "3.8"
# services:

#   # The Application
#   app:
#     build:
#       context: ./
#       dockerfile: app.dockerfile
#     working_dir: /var/www
#     volumes:
#       - ./application/:/var/www
#     environment:
#       - "DB_PORT=3306"
#       - "host=localhost"

#   # The Web Server
#   web:
#     build:
#       context: ./
#       dockerfile: web.dockerfile
#     working_dir: /var/www
#     volumes_from:
#       - app
#     links:
#       - app
#     ports:
#       - 8091:80

#   # The Database
#   database:
#     image: mysql:8.0.22
#     volumes:
#       - db:/var/lib/mysql
#     environment:
#       - "MYSQL_DATABASE=todolistdocker"
#       - "MYSQL_USER=root"
#       - "MYSQL_PASSWORD=rewan123"
#       - "MYSQL_ROOT_PASSWORD=rewan123"

#     ports:
#         - "33062:3306"

# volumes:
#   db:




version: '3.8'
services:
  # PHP-FPM - Service
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www

    volumes:
      - ./:/var/www
      - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks:
      - app-network

  # NGINX - Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true

    ports:
      - "8100:80"
      - "8143:443"

    volumes:
      - ./:/var/www
      - ./docker-files/nginx/conf.d/:/etc/nginx/conf.d/

    networks:
      - app-network

  # MariaDB - Service
  db:
    image: mysql:8.0.22
    container_name: db1
    restart: unless-stopped
    tty: true

    ports:
      - "3307:3306"

    environment:
      MYSQL_DATABASE: todolistdocker
      MYSQL_ROOT_PASSWORD: rewan123

    volumes:
      - ./mysql/init.sql:/data/application/init.sql
      - mysql_data:/var/lib/mysql

    networks:
      - app-network

# Volumes
# volumes:
#   mariadbdata:
#     driver: local

volumes:
   mysql_data:

# Networks
networks:
  app-network:
    driver: bridge
